//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMovi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direct
    {
        public int DirectorID { get; set; }
        public int MovieID { get; set; }
        public string DirectorType { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
